-- Create table to load data raw
CREATE TABLE `list_raw` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `book_id` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `title` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `author` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `author_lf` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `author_additional` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isbn` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isbn13` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rating_my` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rating_average` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `publisher` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `binding` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `page_count` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `publication_year` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `publication_year_original` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `read_date` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `added_date` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bookshelves` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bookshelves_positions` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bookshelve_exclusive` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `review_my` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `spoiler` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `notes_private` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `read_count` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recommended_for` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recommended_by` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `owned_copies` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `original_purchase_date` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `original_purchase_location` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `condition` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `condition_description` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bcid` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=447 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create user space table
CREATE TABLE `list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `book_id` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `title` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `author` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `author_lf` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `author_additional` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isbn` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isbn13` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `rating_my` tinyint(4) DEFAULT NULL,
  `rating_average` float(3,2) DEFAULT NULL,
  `publisher` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `binding` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `page_count` smallint(6) DEFAULT NULL,
  `publication_year` date DEFAULT NULL,
  `publication_year_original` smallint(6) DEFAULT NULL,
  `read_date` date DEFAULT NULL,
  `added_date` date DEFAULT NULL,
  `bookshelves` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bookshelves_positions` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bookshelve_exclusive` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `review_my` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `spoiler` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `notes_private` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `read_count` tinyint(4) DEFAULT NULL,
  `recommended_for` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recommended_by` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `owned_copies` tinyint(4) DEFAULT NULL,
  `original_purchase_date` date DEFAULT NULL,
  `original_purchase_location` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `condition` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `condition_description` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bcid` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=512 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
