-- Transforms, and loads into table list, the data in table list_raw
INSERT INTO `goodreads`.`list`
(`book_id`,
`title`,
`author`,
`author_lf`,
`author_additional`,
`isbn`,
`isbn13`,
`rating_my`,
`rating_average`,
`publisher`,
`binding`,
`page_count`,
`publication_year`,
`publication_year_original`,
`read_date`,
`added_date`,
`bookshelves`,
`bookshelves_positions`,
`bookshelve_exclusive`,
`review_my`,
`spoiler`,
`notes_private`,
`read_count`,
`recommended_for`,
`recommended_by`,
`owned_copies`,
`original_purchase_date`,
`original_purchase_location`,
`condition`,
`condition_description`,
`bcid`)
SELECT 
    CASE WHEN (`list_raw`.`book_id`='') THEN NULL ELSE `list_raw`.`book_id` END AS book_id,
    CASE WHEN (`list_raw`.`title`='') THEN NULL ELSE `list_raw`.`title` END AS title,
    CASE WHEN (`list_raw`.`author`='') THEN NULL ELSE `list_raw`.`author` END AS author,
    CASE WHEN (`list_raw`.`author_lf`='') THEN NULL ELSE `list_raw`.`author_lf` END AS author_lf,
    CASE WHEN (`list_raw`.`author_additional`='') THEN NULL ELSE `list_raw`.`author_additional` END AS author_additional,
	  CASE WHEN (`list_raw`.`isbn`='' OR `list_raw`.`isbn`='=""') THEN NULL ELSE REPLACE(REPLACE(`list_raw`.`isbn`, '"', ''), '=', '') END AS isbn,
	  CASE WHEN (`list_raw`.`isbn13`='' OR `list_raw`.`isbn13`='=""') THEN NULL ELSE REPLACE(REPLACE(`list_raw`.`isbn13`, '"', ''), '=', '') END AS isbn13,
    CASE WHEN (`list_raw`.`rating_my`='') THEN NULL ELSE CAST(`list_raw`.`rating_my` AS SIGNED INTEGER) END AS rating_my,
	  CASE WHEN (`list_raw`.`rating_average`='') THEN NULL ELSE CAST(`list_raw`.`rating_average` AS DECIMAL(3,2)) END AS rating_average,
    CASE WHEN (`list_raw`.`publisher`='') THEN NULL ELSE `list_raw`.`publisher` END AS publisher,
	  CASE WHEN (`list_raw`.`binding`='') THEN NULL ELSE `list_raw`.`binding` END AS binding,
    CASE WHEN (`list_raw`.`page_count`='') THEN NULL ELSE CAST(`list_raw`.`page_count` AS SIGNED INTEGER) END AS page_count,
    CASE WHEN (`list_raw`.`publication_year`='') THEN NULL ELSE STR_TO_DATE(`list_raw`.`publication_year`, '%Y') END AS publication_year,
    CASE WHEN (`list_raw`.`publication_year_original`='') THEN NULL ELSE CAST(`list_raw`.`publication_year_original` AS SIGNED INTEGER) END AS publication_year_original,
    CASE WHEN (`list_raw`.`read_date`='') THEN NULL ELSE STR_TO_DATE(`list_raw`.`read_date`, '%Y/%m/%d') END AS read_date,
	  CASE WHEN (`list_raw`.`added_date`='') THEN NULL ELSE STR_TO_DATE(`list_raw`.`added_date`, '%Y/%m/%d') END AS added_date,
    CASE WHEN (`list_raw`.`bookshelves`='') THEN NULL ELSE `list_raw`.`bookshelves` END AS bookshelves,
    CASE WHEN (`list_raw`.`bookshelves_positions`='') THEN NULL ELSE `list_raw`.`bookshelves_positions` END AS bookshelves_positions,
    CASE WHEN (`list_raw`.`bookshelve_exclusive`='') THEN NULL ELSE `list_raw`.`bookshelve_exclusive` END AS bookshelve_exclusive,
    CASE WHEN (`list_raw`.`review_my`='') THEN NULL ELSE `list_raw`.`review_my` END AS review_my,
    CASE WHEN (`list_raw`.`spoiler`='') THEN NULL ELSE `list_raw`.`spoiler` END AS spoiler,
    CASE WHEN (`list_raw`.`notes_private`='') THEN NULL ELSE `list_raw`.`notes_private` END AS notes_private,
    CASE WHEN (`list_raw`.`read_count`='') THEN NULL ELSE CAST(`list_raw`.`read_count` AS SIGNED INTEGER) END AS read_count,
    CASE WHEN (`list_raw`.`recommended_for`='') THEN NULL ELSE `list_raw`.`recommended_for` END AS recommended_for,
    CASE WHEN (`list_raw`.`recommended_by`='') THEN NULL ELSE `list_raw`.`recommended_by` END AS recommended_by,
    CASE WHEN (`list_raw`.`owned_copies`='') THEN NULL ELSE CAST(`list_raw`.`owned_copies` AS SIGNED INTEGER) END AS owned_copies,
    CASE WHEN (`list_raw`.`original_purchase_date`='') THEN NULL ELSE STR_TO_DATE(`list_raw`.`original_purchase_date`, '%Y/%m/%d') END AS original_purchase_date,
    CASE WHEN (`list_raw`.`original_purchase_location`='') THEN NULL ELSE `list_raw`.`original_purchase_location` END AS original_purchase_location,
    CASE WHEN (`list_raw`.`condition`='') THEN NULL ELSE `list_raw`.`condition` END AS `condition`,
    CASE WHEN (`list_raw`.`condition_description`='') THEN NULL ELSE `list_raw`.`condition_description` END AS condition_description,
    CASE WHEN (`list_raw`.`bcid`='') THEN NULL ELSE `list_raw`.`bcid` END AS bcid
FROM `goodreads`.`list_raw`;
